import Head from "next/head";
import styles from "../styles/Home.module.css";

// ------------- IMPORT MODULE -----------------
// import ReactChild from "../components/ReactChild";
// // @ts-ignore
// const Header = (await import("fe1/header")).default;
// console.log(Header.toString());
import dynamic from "next/dynamic";
const Header = dynamic(
  () => {
    // @ts-ignore
    return import("fe1/header");
  },
  { ssr: false }
);

let stringFormat: any;
if (process.browser) {
  // @ts-ignore
  stringFormat = (await import("fe1/stringFormat")).default;
}
// // @ts-ignore
// const stringFormat = (await import("fe1/stringFormat")).default;
// const stringFormat = dynamic(
//   () => {
//     // @ts-ignore
//     return import("fe1/stringFormat");
//   },
//   { ssr: false }
// );

// ------------- REACT REMOTE -------------------
// @ts-ignore
const ReactRemoteComponent = dynamic(() => import("childReact/Nav"), {
  ssr: false,
});

export default function Home() {
  // console.log(stringFormat.toString());
  const text = process.browser ? stringFormat("Johnny Doe Degh Jr.") : "Hehe";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <br />
        <p>Test func from fe1: {text}</p>
        <br />
        <ReactRemoteComponent></ReactRemoteComponent>
      </main>
    </>
  );
}
